### ISSUE TITLE
Default grepprg is suboptimal

### ISSUE THREAD

**Issue by mtglsk** [tpope/vim-sensible#115]
Default is `grepprg=grep -n $* /dev/null` (at least on linux).

Even something like: `grepprg=grep\ -IHnr\ --color=never` is much more optimal imho.

**Comment by tpope** [comment]
None of your additions are 100% portable. Furthermore:

* `/dev/null` addresses the need for `-H` *and* handily improves the case where you forget a file name.
* `--color=never`: you really have to go out of your way to make this necessary.
* `-I`: I don't see the advantage, and it might confuse people.

Personally I do add `-r` in my own config, but I don't think Sensible should take ownership here.

**Comment by mtglsk** [comment]
> /dev/null addresses the need for -H and handily improves the case where you forget a file name.

With `-H` i can just grep to find all occurrences of a pattern everywhere in my current pwd. Unless someone has ginormous file amount to work with, i don't see this as a problem. Wouldn't someone use vimgrep to search current files?

> `-I`: I don't see the advantage, and it might confuse people.

Ignoring binary offers a substantial speed boost (also ignoring case speeds things up a lot, but this is a lot more controversial of a change). I doubt many people using vim search through binaries. Isn't this what basically ag / ack do along with some exclude dirs? I heard though that grep is stupid enough to sometimes confuse legit log files with binaries.

Although i do agree that this probably not portable given mac os x outdated gnu utils.

**Comment by tpope** [comment]
FWIW I didn't realize `-rH` changes the usual stdin default to the current directory.

**Comment by bsandrow** [comment]
@mtglsk: I know this is a closed topic, but I had to mention that this:

> Although i do agree that this probably not portable given mac os x outdated gnu utils.

is not right. Mac OSX does not ship with GNU utils, it comes from a BSD base, so its POSIX tools are the _BSD_ utils. Anything not portable with the OSX default versions of (e.g.) grep will probably not work with any of the \*BSDs either.

Maybe you're confused because Mac OSX ships with a very out-dated version of Bash (due to the license switch from GPLv2 to GPLv3)? (Early version of OSX didn't even ship with bash, but _tcsh_ as the default shell)
