### ISSUE TITLE
Use POSIX shell highlighting

### ISSUE THREAD

**Issue by jbro** [tpope/vim-sensible#140]
I've just added `let g:is_posix  = 1` to my vimrc after discovering that Vim apparently still thinks that the default shell is bourne shell, and not a POSIX compatible one.

The thing that annoyed me most, is that Vim as default marks the `$()` syntax as being illegal, even though it's part of the POSIX shell, which led me to find the above mentioned fix.

I don't think that most people who write shell scripts, are targeting a POSIX compatible shell as default, and not bourne shell, so the `let g:is_posix =1` is only sensible :)

**Comment by tpope** [comment]
I hear you. I have the same setting in my own vimrc. I'm hesitant for sensible.vim to take responsibility individual filetype settings.

**Comment by jbro** [comment]
I see your point, and that adding this is the screw without an end. But the default is still annoying :)

**Comment by tpope** [comment]
This was [proposed as a new default behavior](https://github.com/vim/vim/issues/7656) and rejected by the maintainer because some users would prefer Bash instead. I strongly disagree with this decision for multiple reasons:

1. If you are using Bash syntax, you should use a Bash shebang (which the syntax file detects). Otherwise you _will_ get screwed.
2. Even if you do prefer Bash syntax, POSIX is still closer to Bash than the status quo. Literally zero people would be made unhappy by switching the default.
3. Defaulting to POSIX doesn't mean users would be prohibited from opting into Bash. **Literally zero people would be made unhappy by switching the default.**

So while I remain loathe to meddle in the affairs of filetype plugins, I am tentatively making a one-time exception to mitigate this upstream failure.
