### ISSUE TITLE
set mouse=a

### ISSUE THREAD

**Issue by josephholsten** [tpope/vim-sensible#152]
Personally, I love being able to scroll and reposition cursor with a mouse inside a modern terminal emulator like iTerm. 

Is there a downside I'm not seeing?

http://vimdoc.sourceforge.net/htmldoc/options.html#%27mouse%27

**Comment by Asheq** [comment]
I'm with you, but my guess is that some people might prefer having some or all of their mouse events (e.g. to select text) handled by the terminal itself. (I'm not one of those people)

**Comment by tpope** [comment]
It's great when copy and paste are properly hooked up, but in a world with ssh, tmux, and custom Vim builds that aren't always configured quite right, you sadly can't really count on that. Personally I `:set mouse=nvi`, so I can access the built-in terminal mouse support by pressing `:` when necessary. But that feels a bit too clever to impose on the world.

**Comment by josephholsten** [comment]
@tpope honestly, I haven't seen it broken anywhere since I turned it in my personal configs last year. Can you actually reproduce it working badly, or are you relying on memory? If it is still broken for people, I'd love to go fix it.

(Which might not address all possible misconfigured custom vim builds, but what would?)

**Comment by josephholsten** [comment]
ah! I honestly don't do that ever. I'm mostly after being able to scroll and select text with the mouse. 

Since vim-sensible doesn't `:set clipboard=` to anything, I think users expect the clipboard to be internal without further effort on their part, and this has been clearly communicated: https://github.com/tpope/vim-sensible/issues/145

**Comment by Asheq** [comment]
@josephholsten, I'm not sure you quite understand the ssh scenario. Let's say you open a terminal emulator on your local machine. You ssh into a remote machine and start vim on the remote machine. If you make a visual selection and then use `"*y`, this will copy the selected text into the system clipboard of the _**remote**_ machine where vim is running, NOT your **_local_** machine where your terminal emulator is running.

If you need to copy into the system clipboard of your local machine, a simple workaround is to select text via the mouse which is handled by your local terminal emulator by default. If you make vim handle it (via `mouse=a`), this workaround wouldn't work.

We can always set `mouse=a` in our personal configs (I have this; I also like @tope's `mouse=nvi ` idea), but I don't think we can expect vim-sensible to do it for us since there are many users who have to ssh and do other things where they would prefer having mouse events handled by their terminal emulator.

**Comment by tpope** [comment]
Thanks for that thorough explanation @Asheq!

**Comment by josephholsten** [comment]
Ah I can confirm by:
- `ssh remote-machine`
- `vi remote-file`
- `:set mouse=a`
- Select text with your mouse
- Then the local terminal emulator fails to present a "Copy" operation, either for Ctrl-C/Cmd-C or from a menu.

**Comment by 0matgal0** [comment]
_> Then the local terminal emulator fails to present a "Copy" operation, either for Ctrl-C/Cmd-C or from a menu._

Not even with Shift pressed?

**Comment by mikelward** [comment]
As well as breaking copy/paste, it also breaks my terminal's right click menu.
