### ISSUE TITLE
vim-sensible causes indentation when typing "#" in YAML files?

### ISSUE THREAD

**Issue by johanneskastl** [tpope/vim-sensible#188]
Hi Tim,

I have the following in my .vimrc, to disable the autoindenting when I enter a hash (`#`) in a YAML file.

This is what I want:

```
foo:
  #bar: test
```

This is what the indentation is doing:

```
foo:
    #bar: test
```

I tested the workarounds that the internet has to offer, such as setting `indentkeys-=0#` for the yaml FileType.

But this did not work, until I removed vim-sensible from my `~/.vim/pack/` folder completely.

Not sure if this behaviour is intended, if so, can it be disabled? Because I found vim-sensible really nice to use, hence I would like to keep using it... :-)

For the record, here is the snippet from my `~/.vimrc` that configures the YAML behaviour:

```
au! BufNewFile,BufFilePre,BufReadPost *.{yml,yaml} set filetype=yaml                                                                                                                         
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab autoindent smartindent 
```

Thanks in advance!

**Comment by mmrwoods** [comment]
This might simply be because sensible.vim runs the `:filetype` command to enable filetype detection and filetype specific indentation rules in VIm (which are not enabled by default, see `:help :filetype`). The YAML indent expression bundled with Vim is more likely to be the problem. Personally, I disable this because it has some, IMHO, unintuitive behaviour, similar to what you've described (though I have not observed your exact issue).

Try using sensible.vim again, and update your autocmd to unset the YAML indent expression, e.g.

```
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab autoindent smartindent indentexpr=
```

btw, when using sensible.vim you should not need `au! BufNewFile,BufFilePre,BufReadPost *.{yml,yaml} set filetype=yaml`, Vim should automatically detect the filetype as yaml for *.yml and *.yaml files.

**Comment by tpope** [comment]
> This might simply be because sensible.vim runs the `:filetype` command to enable filetype detection and filetype specific indentation rules in VIm (which are not enabled by default, see `:help :filetype`).

I agree that file type detection is the first thing to look at. Try turning it on in your vimrc, and try commenting it out in sensible.

> The YAML indent expression bundled with Vim is more likely to be the problem.

Not impossible, but this is extremely trivial YAML, I can't imagine something so fundamental has gone unnoticed. Check `'indentexpr'` when it's working and when it's not and see if they're the same. And double check that something isn't overriding `'shiftwidth'`.

> ```
> smartindent
> ```

If you want to talk "unintuitive", we should talk about the name of this option. Do y'all have the slightest idea what that does? From the help:

```
			     *'smartindent'* *'si'* *'nosmartindent'* *'nosi'*
'smartindent' 'si'	boolean	(default off)
			local to buffer
	Do smart autoindenting when starting a new line.  Works for C-like
	programs, but can also be used for other languages.
```

Indenting YAML like it's C produces results 100 times more fucked up than any `'indentexpr'`. It doesn't even do `#` right because it thinks it's for the pre-processor!

**Comment by mmrwoods** [comment]
Apologies, I stumbled upon this GH issue while searching for something else and jumped to conclusions as the behaviour reminded me of something I'd seen with the yaml indentexpr, I didn't even look at the docs for smartindent.

**Comment by johanneskastl** [comment]
Thanks @tpope @mmrwoods  for the help. For now I have disabled the `smartindent` in the YAML line and will see, if this works reliably.

```
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab autoindent indentkeys-=0# indentkeys-=<:>
```
