### ISSUE TITLE
Spaces for tabs

### ISSUE THREAD

**Issue by mshron** [tpope/vim-sensible#66]
I prefer spaces over tabs. I know this is a sensitive issue for some people; is there a way to make `vim-sensible` check to see if tabs-as-spaces is already being set in the vimrc and to ignore it if so?

**Comment by ilium007** [comment]
Sorry to drag this up again but I am getting tabs instead of spaces. I am testing in a 'sh' file type (after I noticed weird tab spacing in a yaml filetype. `

I have commented out the usual settings for tabs to spaces that I would have for this in my .vimrc:

```shell
set nocompatible

filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

"my bundles
Bundle 'tpope/vim-sensible'
Bundle 'bling/vim-airline'
Bundle 'Raimondi/delimitMate'
Bundle 'hynek/vim-python-pep8-indent'

"color schemes
Bundle 'altercation/vim-colors-solarized'

"set tabstop=4       " number of visual spaces per TAB
"set softtabstop=4   " number of spaces in tab when editing
"set expandtab       " tabs are spaces

filetype on
syntax on
filetype plugin indent on

syntax enable
set background=dark
colorscheme solarized
let g:solarized_contrast = "high"

"toggle paste mode
set pastetoggle=<F2>

"no audible bell
set visualbell```

When I open a new .sh file, for example and enter insert mode, I hit tab and get a TAB not 4 spaces as I would expect. It's definitely a TAB because if I move the cursor back to the left after hitting the TAB key its jumps back the TAB distance, not singularly over 4 spaces.

**Comment by tpope** [comment]
If you don't set `'expandtab'`, you will get the Vim default of tabs.

**Comment by ilium007** [comment]
Ok cool - so that isn't something that is set in your vim-sensible ? Thanks for the code by the way !
