### ISSUE TITLE
swap file handling: editexisting and DiffOrig

### ISSUE THREAD

**Issue by Konfekt** [tpope/vim-sensible#86]
How about the other macro supplied with Vim, editexisting.vim, that, when trying to edit a file for which there is already a swap file, spawns the Vim instance responsible for the swap file and opens the file there. That is adding the following snippet to .vimrc:

```
if !exists('*EditExisting')  && findfile('plugin/editexisting.vim', &rtp) ==# ''
  runtime! macros/editexisting.vim
endif
```

While we're at it, how about addig the `DiffOrig` command of the examplevimrc.vim supplied with Vim that is convenient for all other instances of swap files handling.

**Comment by dnwe** [comment]
:+1: for editexisting.vim - very useful macro that not many people are aware of

**Comment by aidecoe** [comment]
+1 for editexisting.vim and DiffOrig

**Comment by ashemedai** [comment]
DiffOrig is at least part of defaults.vim with vim 8.

**Comment by tpope** [comment]
EditExisting breaks some guarantees like `gvim -f` waiting until exit. It also only applies to GVim users, and to the workflow where you open every file in its own instance (instead of, for example, `--remote`), which frankly kinda sucks. I mean if you want that, more power to you, but it's about as far as you can get from a good default.

Since defaults.vim provides `:DiffOrig`, and it doesn't really hurt anything, I have caved on that.
